from .pace_ops import compute_loss_pace, compute_loss_pace_lazy_half, compute_loss_pace_fast, MultiplicativeNoiseAdapter
from .sharable_dropout import ensure_sharable_drop_path
from .residual_adapters import inject_residual_adapter, ResidualAdapter, get_adapters_and_block_ids